# GitHub Actions workflow for deploying Vite React app to GitHub Pages
# This workflow builds the app and deploys it automatically on push to main branch

name: Deploy to GitHub Pages

on:
  # Trigger deployment on push to main branch
  push:
    branches: [ "main" ]
  
  # Allow manual workflow dispatch from GitHub UI
  workflow_dispatch:

# Set permissions for GitHub token to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job - compiles the React app
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4
      
      # Setup Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      # Setup GitHub Pages configuration
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Install project dependencies
      - name: Install dependencies
        run: npm ci
      
      # Build the application for production
      - name: Build
        run: npm run build
      
      # Upload build artifacts for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  # Deploy job - publishes the built app to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
